In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
red_basket = pd.read_csv('/home/pirl/와인사업기획/rwsb.csv',encoding='cp949')
red_basket.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2030307,42329,1,0,Private Selection Pinot Noir,28,5.0,4,2,4,11,19.0
1,2030307,7160,2,0,Clear Cups,111,17.0,4,2,4,11,19.0
2,3288630,12013,3,0,Pinot Noir,28,5.0,21,8,2,13,18.0
3,3288630,38444,2,0,Chardonnay,62,5.0,21,8,2,13,18.0
4,3288630,16139,4,0,Clara,27,5.0,21,8,2,13,18.0

In [3]:
white_basket = pd.read_csv('/home/pirl/와인사업기획/wwsb.csv',encoding='cp949')
white_basket.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1737705,47141,2,0,Cola,77,7.0,17,1,2,13,NaN
1,1737705,7350,1,0,Natural Lime Flavor Sparkling Mineral Water,115,7.0,17,1,2,13,NaN
2,1737705,17762,3,0,Light Oaked Chardonnay,62,5.0,17,1,2,13,NaN
3,1681401,16797,5,0,Strawberries,24,4.0,17,2,5,10,3.0
4,1681401,42356,4,0,Strawberry Preserves,88,13.0,17,2,5,10,3.0

In [4]:
df_products = pd.read_csv('/home/pirl/와인사업기획/grocery_products.csv',encoding='cp949')
df_products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19.0
1,2,All-Seasons Salt,104,13.0
2,3,Robust Golden Unsweetened Oolong Tea,94,7.0
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1.0
4,5,Green Chile Anytime Sauce,5,13.0

In [5]:
df_reds = df_products.loc[df_products.aisle_id == 28,['product_id','product_name']]
df_reds.head()

     product_id                             product_name
478         479  Most Wanted Cabernet Sauvignon Red Wine
566         567                          Malbec Red Wine
579         580                  Washington State Merlot
597         598            Cabernet Sauvignon California
836         837                        California Merlot

In [6]:
df_whites = df_products.loc[df_products.aisle_id == 62,['product_id','product_name']]
df_whites.head()

      product_id                    product_name
118          119          Chardonnay Paso Robles
248          249  Pinot Grigio, California, 2010
550          551           Riesling, Mosel, 2014
1096        1097   Sonoma County Sauvignon Blanc
1159        1160                    Pinot Grigio

In [7]:
df_spaks = df_products.loc[df_products.aisle_id == 134,['product_id','product_name']]
df_spaks.head()

      product_id                    product_name
51            52             Mirabelle Brut Rose
149          150                       Brut Ros챕
1807        1808                       Champagne
2021        2022  Brut Cuvee Sparkling Champagne
2215        2216            California Champagne

In [23]:
from collections import Counter
import re

# p = re.compile('[a-zA-Z]+')
wine_words = []

for wine in df_reds.product_name.values:
    wine_words += map(lambda x: x.lower(),re.findall(r'[A-Za-z]+',wine))

In [100]:
for wine in df_whites.product_name.values:
    wine_words += map(lambda x: x.lower(),wine.split())

In [96]:
for wine in df_spaks.product_name.values:
    wine_words += map(lambda x: x.lower(),wine.split())

In [24]:
grape = Counter(wine_words)

In [25]:
sorted(grape.items(),key=lambda x:x[1],reverse=True)

[('cabernet', 50),
 ('wine', 48),
 ('sauvignon', 46),
 ('red', 45),
 ('noir', 34),
 ('pinot', 33),
 ('california', 31),
 ('merlot', 23),
 ('zinfandel', 21),
 ('valley', 18),
 ('blend', 14),
 ('coast', 12),
 ('reserve', 10),
 ('sonoma', 9),
 ('napa', 9),
 ('central', 8),
 ('chianti', 8),
 ('malbec', 7),
 ('s', 7),
 ('shiraz', 7),
 ('county', 6),
 ('old', 6),
 ('alexander', 5),
 ('organic', 5),
 ('paso', 5),
 ('robles', 5),
 ('syrah', 5),
 ('d', 4),
 ('classico', 4),
 ('zin', 4),
 ('vine', 4),
 ('collection', 4),
 ('label', 4),
 ('monterey', 3),
 ('sweet', 3),
 ('coastal', 3),
 ('de', 3),
 ('vintner', 3),
 ('riserva', 3),
 ('russian', 3),
 ('river', 3),
 ('vines', 3),
 ('vintage', 3),
 ('toscana', 3),
 ('dry', 2),
 ('sherry', 2),
 ('mendoza', 2),
 ('meritage', 2),
 ('grape', 2),
 ('dark', 2),
 ('rioja', 2),
 ('tempranillo', 2),
 ('decoy', 2),
 ('lodi', 2),
 ('moscato', 2),
 ('chardonnay', 2),
 ('santa', 2),
 ('rosso', 2),
 ('north', 2),
 ('diamond', 2),
 ('crush', 2),
 ('reserva', 2),
 ('petite', 2),
 ('sirah', 2),
 ('black', 2),
 ('estates', 2),
 ('barbera', 2),
 ('cotes', 2),
 ('du', 2),
 ('rhone', 2),
 ('grand', 2),
 ('indian', 2),
 ('wells', 2),
 ('bordeaux', 2),
 ('garnacha', 2),
 ('most', 1),
 ('wanted', 1),
 ('washington', 1),
 ('state', 1),
 ('platinum', 1),
 ('jumilla', 1),
 ('very', 1),
 ('bristol', 1),
 ('cream', 1),
 ('diablo', 1),
 ('vin', 1),
 ('pays', 1),
 ('oc', 1),
 ('mendocino', 1),
 ('delicious', 1),
 ('kenwood', 1),
 ('ml', 1),
 ('midnight', 1),
 ('asti', 1),
 ('docg', 1),
 ('director', 1),
 ('cut', 1),
 ('y', 1),
 ('block', 1),
 ('barbara', 1),
 ('cardinal', 1),
 ('beastly', 1),
 ('stella', 1),
 ('semi', 1),
 ('primitivo', 1),
 ('lambrusco', 1),
 ('carbernet', 1),
 ('ducale', 1),
 ('b', 1),
 ('side', 1),
 ('the', 1),
 ('prisoner', 1),
 ('casillero', 1),
 ('del', 1),
 ('dialblo', 1),
 ('paisano', 1),
 ('tuscany', 1),
 ('essential', 1),
 ('green', 1),
 ('a', 1),
 ('trois', 1),
 ('silk', 1),
 ('h', 1),
 ('horse', 1),
 ('heaven', 1),
 ('hills', 1),
 ('carneros', 1),
 ('ancient', 1),
 ('heritage', 1),
 ('claret', 1),
 ('knights', 1),
 ('south', 1),
 ('australia', 1),
 ('bv', 1),
 ('maraia', 1),
 ('monferr', 1),
 ('italy', 1),
 ('harvest', 1),
 ('marlborough', 1),
 ('domaine', 1),
 ('garrigon', 1),
 ('fruity', 1),
 ('sangria', 1),
 ('julia', 1),
 ('vineyard', 1),
 ('woodbridge', 1),
 ('frontera', 1),
 ('creek', 1),
 ('force', 1),
 ('of', 1),
 ('nature', 1),
 ('superiore', 1),
 ('sin', 1),
 ('cellar', 1),
 ('sangiovese', 1),
 ('by', 1),
 ('duckhorn', 1),
 ('sleepy', 1),
 ('hollow', 1),
 ('deadly', 1),
 ('zins', 1),
 ('alba', 1),
 ('cote', 1),
 ('rouge', 1),
 ('france', 1),
 ('rich', 1),
 ('franc', 1),
 ('burgundy', 1),
 ('tapestry', 1),
 ('broquel', 1),
 ('velvet', 1),
 ('reserves', 1),
 ('incredible', 1),
 ('cristina', 1),
 ('los', 1),
 ('osos', 1),
 ('louis', 1),
 ('jadot', 1),
 ('kali', 1),
 ('hart', 1),
 ('cashmere', 1),
 ('villa', 1),
 ('anderson', 1),
 ('paraduxx', 1),
 ('z', 1),
 ('columbia', 1),
 ('starmont', 1),
 ('argentina', 1),
 ('rutherford', 1),
 ('phantom', 1),
 ('gsm', 1),
 ('protocolo', 1),
 ('vino', 1),
 ('la', 1),
 ('tierra', 1),
 ('tinto', 1),
 ('sultry', 1),
 ('bistro', 1),
 ('style', 1),
 ('hillside', 1),
 ('vineyards', 1),
 ('winemaker', 1),
 ('private', 1),
 ('selection', 1),
 ('hot', 1),
 ('to', 1),
 ('trot', 1),
 ('white', 1),
 ('american', 1),
 ('terra', 1),
 ('oro', 1),
 ('amador', 1),
 ('oregon', 1),
 ('silver', 1),
 ('chillable', 1),
 ('house', 1),
 ('montepulciano', 1),
 ('liar', 1),
 ('dice', 1),
 ('cork', 1),
 ('dancer', 1),
 ('avant', 1),
 ('zero', 1),
 ('sulfites', 1),
 ('des', 1),
 ('rose', 1),
 ('grenache', 1),
 ('cinsault', 1),
 ('pinto', 1),
 ('concord', 1),
 ('crianza', 1),
 ('non', 1),
 ('alcoholic', 1),
 ('natural', 1)]

In [36]:
wine_list = ['cabernet','sauvignon','pinot','noir','zinfandel','merlot',
             'chianti','malbec','shiraz','syrah','zin','sherry','tempranillo',
             'moscato','chardonnay','sirah','carbernet']

# cabernet sauvignon,pinot noir, zinfandel, merlot, chianti, malbec,(shiraz,syrah), sherry, tempranillo

In [51]:
df_reds.product_name.values

array(['Most Wanted Cabernet Sauvignon Red Wine', 'Malbec Red Wine',
       'Washington State Merlot', 'Cabernet Sauvignon California',
       'California Merlot', 'Cabernet Sauvignon, Central Coast, 2011',
       'Merlot, Alexander Valley, Sonoma County, 2009', 'Platinum Merlot',
       'Jumilla Red Wine', 'Very Dry Sherry', 'Merlot Wine',
       'Malbec Mendoza', 'Pinot Noir Monterey', 'Bristol Cream Sherry',
       'Sweet Red', 'Meritage Wine', 'Coastal Pinot Noir',
       'Diablo Cabernet', "Pinot Noir, Vin de Pays d'Oc, 2006",
       'Organic Mendocino Cabernet Sauvignon',
       'Grape Wine, Delicious Red',
       'Kenwood Cabernet Sauvignon Sonoma Valley 750 Ml',
       'Cabernet Sauvignon Alexander Valley',
       'Midnight California Dark Red Wine Blend', 'Malbec 2013',
       'Rioja Tempranillo', 'Pinot Noir, California, 2011', 'Decoy Red',
       'California Cabernet Sauvignon Wine',
       "Vintner's Reserve Zinfandel 2012", 'Chianti Riserva Wine',
       'Pinot Noir, California 2010', 'Chianti Classico, 2006',
       'Russian River Valley Reserve Pinot Noir',
       'Zin, Old Vine, Lodi, 2008', 'Cabernet Sauvignon Sonoma County',
       'Merlot', "Moscato, D'Asti, DOCG, 2011", 'Red Blend',
       "Director's Cut Pinot Noir", 'Napa Valley Cabernet Sauvignon',
       'Chardonnay Y Block Santa Barbara',
       'Cardinal Zin Beastly Old Vines Zinfandel',
       'Red Wine, Dark, California, 2013', 'Pinot Noir California',
       'Stella Rosso, Semi-Sweet',
       'Cabernet Sauvignon, North Coast, 2011',
       'Primitivo Red Wine Zinfandel', 'Lambrusco', 'Organic Malbec',
       'Cabernet Sauvignon, California, 2011',
       'Diamond Collection Red Label Zinfandel', 'Reserve Shiraz Wine',
       'Alexander Valley Reserve Cabernet Sauvignon',
       'Coastal Crush Red Central Coast',
       "Vintner's Reserve Carbernet Sauvignon",
       'Riserva Ducale Chianti Classico', 'B Side Red',
       'California Red Wine', 'The Prisoner Blend', 'Rioja Reserva',
       'Organic Pinot Noir', 'Crush Red Blend', 'Casillero del Dialblo',
       'Cabernet Sauvignon, Paso Robles, 2012', 'Pinot Noir',
       'California Paisano', 'Chianti Classico Tuscany',
       'Reserva Malbec Red Wine', 'Russian River Pinot Noir Wine',
       'Alexander Valley Cabernet Sauvignon Wine',
       'Pinot Noir, California', '337 Cabernet Sauvignon Wine',
       'Essential Red', 'Sonoma Pinot Noir Wine',
       'Cabernet Sauvignon 2015', 'Green Label Syrah Shiraz',
       'A Trois Silk Red', 'California Pinot Noir', 'Red Blend Wine',
       'Cabernet Sauvignon, H3 Collection, Horse Heaven Hills',
       'Carneros Pinot Noir', 'Syrah Paso Robles',
       'Ancient Vines Zinfandel', 'Zinfandel Heritage',
       'Cabernet Sauvignon, California', 'California Petite Sirah',
       'Claret, Black Label, 2006', 'Merlot Napa Valley, 2004',
       'Knights Valley Cabernet Sauvignon', 'Merlot, California, 2007',
       'Shiraz, South Australia, Vintage 2008', 'Napa Valley Merlot',
       'BV Coastal Estates Merlot', 'Maraia Barbera Monferr Italy',
       'Sonoma Zinfandel', 'Harvest Red Blend', 'Pinot Noir Marlborough',
       'Cabernet Sauvignon California 2008',
       'California Collection Cabernet Sauvignon Wine',
       'Domaine de Garrigon Cotes du Rhone',
       'Sonoma County Cabernet Sauvignon', 'Chianti Classico',
       '667 Pinot Noir', 'Fruity Red Sangria', 'Petite Sirah',
       'Cabernet Sauvignon California 2007',
       'Grand Estates Cabernet Sauvignon', 'Zinfandel, California, 2010',
       "Julia's Vineyard Pinot Noir", 'Pinot Noir Wine',
       'Old Vines Zinfandel Wine', 'Zinfandel, Lodi, California',
       'Woodbridge Cabernet Sauvignon', 'Frontera Chardonnay',
       'Cabernet Sauvignon, Vintage 2011', 'Zinfandel Dry Creek',
       'Napa Valley Zinfandel Wine', 'Force Of Nature Red Paso Robles',
       'Monterey County Pinot Noir', 'Merlot California',
       'Chianti Superiore', 'Sin Zin',
       'Cabernet Sauvignon, California, 2006', 'Reserve Pinot Noir',
       'Cellar 1879 Red Blend', 'Indian Wells Cabernet Sauvignon Wine',
       'Pinot Noir, Central Coast, 2006',
       'Cabernet Sauvignon Paso Robles 2005', 'Old Vine Zinfandel',
       'Sangiovese', 'Merlot, California, 2004', 'Malbec',
       'Cabernet Sauvignon, North Coast, 2012', 'Cabernet',
       'Sweet Red Wine', 'Decoy By Duckhorn Merlot',
       'Sleepy Hollow Pinot Noir', 'Meritage',
       'Pinot Noir, California, 2010', 'Russian River Pinot Noir',
       '7 Deadly Zins', "Barbera D' Alba",
       'California Cabernet Sauvignon', 'Cote Du Rhone Rouge France',
       'Sonoma Coast Pinot Noir', 'Zinfandel Wine', 'Rich Red Blend',
       'Cabernet Franc', 'Burgundy', 'Tapestry Napa Valley',
       'Old Vine Zin', 'Cabernet Sauvignon', '2013 Zinfandel Red Wine',
       'Broquel Malbec', 'California Red Velvet Wine', 'Black',
       'Red Wine Blend', 'Napa Reserves Cabernet Sauvignon',
       'Incredible Red Zinfandel', 'Santa Cristina Rosso Toscana',
       'Merlot, California 2013', 'Merlot, Central Coast',
       'Los Osos Merlot', 'Shiraz', 'Louis Jadot',
       'Reserve Cabernet Sauvignon Wine', 'Kali Hart Pinot Noir',
       'Cashmere', 'Grand Reserve Sonoma County Merlot',
       'Villa Toscana Wine', 'Shiraz Cabernet',
       'Anderson Valley Pinot Noir', '2003 Bordeaux',
       "Vintner's Reserve Syrah Wine", 'Paraduxx Z Red Blend', '2010',
       'Old Vine Zinfandel Wine', 'Moscato, Red, California',
       'Merlot, Columbia Valley, 2007',
       'Starmont Cabernet Sauvignon Napa Valley',
       'Cabernet Sauvignon, Mendoza, Argentina, 2009',
       'Rutherford Cabernet Sauvignon Wine', 'Merlot Napa Valley',
       'Phantom Red', 'GSM, Central Coast, Vintage: 2011',
       'Cabernet Sauvignon, California, 2005', 'Tempranillo',
       'Protocolo Vino de la Tierra Tinto',
       'Sultry Red Bistro Style Wine', 'Garnacha Red Wine', 'Syrah',
       'Shiraz Wine', 'Zinfandel', 'Toscana Hillside Vineyards Red',
       "Red Blend Winemaker's Blend", 'Cabernet Sauvignon Napa Valley',
       'Cabernet Sauvignon, Central Coast, 2007',
       'Private Selection Pinot Noir', 'Central Coast Cabernet Sauvignon',
       'Reserve Merlot Wine', 'Shiraz Cabernet Sauvignon Wine',
       'Hot To Trot Red Blend', 'Chianti', 'Cabernet Paso Robles',
       'Merlot, California', 'White Zinfandel, American',
       "Terra D'oro Zinfandel Amador County", 'Oregon Pinot Noir',
       'Pinot Noir Sonoma Coast',
       'Diamond Collection Silver Label Pinot Noir Wine', 'Red',
       'Chillable Red House Wine', 'Bordeaux',
       'Montepulciano Riserva Red Wine',
       'Alexander Valley Cabernet Sauvignon', "Liar's Dice Zinfandel",
       'Cork Dancer Pinot Noir', 'Central Coast Merlot',
       'Indian Wells Merlot', 'Red Wine', 'Chianti Wine',
       'Avant Red Wine Blend', 'Organic Zero Sulfites Red Wine',
       'Garnacha', 'Cotes Des Rose Grenache Cinsault-Syrah',
       'Pinto Noir, Monterey, 2007', 'Concord Grape',
       'Red Wine, Crianza, 2009', 'Non-Alcoholic Cabernet Sauvignon',
       'Cabernet Sauvignon Wine', 'Organic Natural Red'], dtype=object)

In [86]:
grape_name_wine = set()

for grape in wine_list:
    for wine,index in zip(df_reds.product_name.values,df_reds.product_name.index):
        if(grape in wine.lower()) == True:
            grape_name_wine.add(index)

In [88]:
len(grape_name_wine)

169