In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn import metrics
from sklearn.preprocessing import scale

In [2]:
data = pd.read_csv("./통신고객이탈.csv", engine="python")
data.head()
data.loc[data["CHURN"] == "Active","CHURN"] = 0
data.loc[data["CHURN"] == "Churned","CHURN"] = 1
data.head()

,CHURN,CUSTOMER_ID,GENDER,AGE,CHARGE_TYPE,HANDSET,USAGE_BAND,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME
0,0,K102990,F,31,CAT 100,ASAD170,Med,33.33,6,218,379.8,9,21.6,366,632.4
1,0,K103280,M,27,CAT 100,S50,Med,30.87,10,373,656.4,11,28.0,411,810.4
2,0,K103660,M,27,CAT 100,ASAD170,Med,49.40,11,260,582.0,0,0.0,265,614.1
3,0,K103730,M,61,CAT 100,ASAD170,Med,48.60,1,294,661.8,14,101.5,326,844.0
4,0,K104560,F,52,CAT 100,S50,Med,56.03,0,221,555.6,7,25.0,274,673.0

In [3]:
data.isnull().sum()

CHURN                 0
CUSTOMER_ID           0
GENDER                0
AGE                   0
CHARGE_TYPE           0
HANDSET               0
USAGE_BAND            0
SERVICE_DURATION      0
DROPPED_CALLS         0
PEAK_CALLS_NO         0
PEAK_CALLS_TIME       0
WEEKEND_CALLS_NO      0
WEEKEND_CALLS_TIME    0
TOTAL_CALLS_NO        0
TOTAL_CALLS_TIME      0
dtype: int64

In [4]:
np.random.seed(seed=1234)
msk = np.random.rand(data.shape[0],) < 0.7
df_train = data[msk]
df_test = data[~msk]

print("train_data_size:",df_train.shape)
print("test_data_size:",df_test.shape)

train_data_size: (635, 15)
test_data_size: (295, 15)

In [5]:
df_const_train = sm.add_constant(df_train)
df_const_train.head()

,const,CHURN,CUSTOMER_ID,GENDER,AGE,CHARGE_TYPE,HANDSET,USAGE_BAND,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME
0,1.0,0,K102990,F,31,CAT 100,ASAD170,Med,33.33,6,218,379.8,9,21.6,366,632.4
1,1.0,0,K103280,M,27,CAT 100,S50,Med,30.87,10,373,656.4,11,28.0,411,810.4
2,1.0,0,K103660,M,27,CAT 100,ASAD170,Med,49.40,11,260,582.0,0,0.0,265,614.1
5,1.0,0,K105530,M,51,CAT 100,S80,Med,49.43,3,289,486.6,1,31.8,427,903.3
6,1.0,0,K106210,F,30,CAT 100,ASAD170,Med,32.30,6,427,729.6,12,52.8,490,907.2

In [6]:
# df_const_train["USAGE_BAND"].value_counts()
# df_const_train.drop("CUSTOMER_ID",axis=1)

In [7]:
log_model = sm.Logit.from_formula("""CHURN ~ C(GENDER) + AGE + C(CHARGE_TYPE) + C(HANDSET) + C(USAGE_BAND) +
                                    SERVICE_DURATION + DROPPED_CALLS + PEAK_CALLS_NO+PEAK_CALLS_TIME + 
                                    WEEKEND_CALLS_NO + WEEKEND_CALLS_TIME + TOTAL_CALLS_NO + TOTAL_CALLS_TIME + 1""",
                                 df_const_train)
# log_model = sm.Logit.from_formula("CHURN ~ AGE + 1",
#                                   df_const_train.drop("CUSTOMER_ID",axis=1))
log_res = log_model.fit(method="bfgs")
print(log_res.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.261293
         Iterations: 35
         Function evaluations: 49
         Gradient evaluations: 42
                           Logit Regression Results
==============================================================================
Dep. Variable:                  CHURN   No. Observations:                  635
Model:                          Logit   Df Residuals:                      605
Method:                           MLE   Df Model:                           29
Date:                Sun, 10 Feb 2019   Pseudo R-squ.:                  0.4660
Time:                        22:20:44   Log-Likelihood:                -165.92
converged:                      False   LL-Null:                       -310.70
                                        LLR p-value:                 9.369e-45
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -1.1342      2.139     -0.530      0.596      -5.326       3.058
C(GENDER)[T.M]                -0.5785      0.320     -1.810      0.070      -1.205       0.048
C(CHARGE_TYPE)[T.CAT 200]     -0.1864      0.629     -0.296      0.767      -1.419       1.046
C(CHARGE_TYPE)[T.CAT 50]      -2.4395      1.021     -2.390      0.017      -4.440      -0.439
C(CHARGE_TYPE)[T.Play 100]     0.9210      0.703      1.310      0.190      -0.457       2.299
C(CHARGE_TYPE)[T.Play 300]    -0.2244      0.796     -0.282      0.778      -1.785       1.336
C(HANDSET)[T.ASAD90]           5.4849      0.779      7.039      0.000       3.958       7.012
C(HANDSET)[T.BS110]            1.1184      0.691      1.617      0.106      -0.237       2.474
C(HANDSET)[T.BS210]           -4.3102      2.838     -1.519      0.129      -9.873       1.253
C(HANDSET)[T.CAS30]            5.0987      0.883      5.777      0.000       3.369       6.829
C(HANDSET)[T.CAS60]           -1.1870      2.411     -0.492      0.622      -5.912       3.538
C(HANDSET)[T.S50]              1.6594      0.658      2.522      0.012       0.370       2.949
C(HANDSET)[T.S80]              0.9463      0.715      1.324      0.186      -0.455       2.347
C(HANDSET)[T.SOP10]            1.8914      1.128      1.677      0.093      -0.319       4.101
C(HANDSET)[T.SOP20]            3.1225      1.259      2.479      0.013       0.654       5.591
C(HANDSET)[T.WC95]            -4.7484      4.488     -1.058      0.290     -13.544       4.047
C(USAGE_BAND)[T.Low]           1.1177      2.186      0.511      0.609      -3.166       5.401
C(USAGE_BAND)[T.Med]          -0.5819      1.324     -0.439      0.660      -3.177       2.014
C(USAGE_BAND)[T.MedHigh]      -1.1694      0.949     -1.232      0.218      -3.030       0.691
C(USAGE_BAND)[T.MedLow]        1.1007      1.711      0.643      0.520      -2.253       4.454
C(USAGE_BAND)[T.None]         -0.3415      2.972     -0.115      0.909      -6.167       5.484
AGE                           -0.0317      0.012     -2.626      0.009      -0.055      -0.008
SERVICE_DURATION              -0.0283      0.011     -2.636      0.008      -0.049      -0.007
DROPPED_CALLS                  0.2097      0.040      5.295      0.000       0.132       0.287
PEAK_CALLS_NO                 -0.0008      0.003     -0.300      0.764      -0.006       0.004
PEAK_CALLS_TIME                0.0014      0.001      0.983      0.325      -0.001       0.004
WEEKEND_CALLS_NO              -0.0110      0.013     -0.874      0.382      -0.036       0.014
WEEKEND_CALLS_TIME             0.0073      0.006      1.304      0.192      -0.004       0.018
TOTAL_CALLS_NO                 0.0011      0.002      0.458      0.647      -0.003       0.006
TOTAL_CALLS_TIME              -0.0012      0.002     -0.765      0.444      -0.004       0.002
==============================================================================================

/home/pirl/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1724: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))
/home/pirl/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1724: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))
/home/pirl/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)